# https://esphome.io/components/esphome.html
substitutions:
  boot_state_sync: "true"    # set to false to skip the on-boot DALI state sync
  dali_discovery: "false"    # Disable auto-discovery; we define lights manually

esphome:
  name: dalimaster
  comment: DALI Master
  name_add_mac_suffix: false

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

external_components:
  - source: 
      type: local
      path: components

# Enable Home Assistant API
api:

web_server:
  port: 80

ota:
  - platform: esphome
    password: "nutjes007"

logger:

light:
- platform: dali
  id: Gang_Beneden
  name: "Gang Beneden"
  address: 0x00
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: SLK_B_K
  name: "SLK B K"
  address: 0x01
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Berging
  name: "Berging"
  address: 0x02
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Bed_K
  name: "Bed K"
  address: 0x03
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Bed_B
  name: "Bed B"
  address: 0x04
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Gang_Boven
  name: "Gang Boven"
  address: 0x05
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Speelhoek_Lijn
  name: "Speelhoek Lijn"
  address: 0x06
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Zetel_K
  name: "Zetel K"
  address: 0x07
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Keuken_Links
  name: "Keuken Links"
  address: 0x08
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Keuken_Rechts
  name: "Keuken Rechts"
  address: 0x09
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Zetel_B
  name: "Zetel B"
  address: 0x0a
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Speelhoek_Muur
  name: "Speelhoek Muur"
  address: 0x0b
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Speelhoek_Raam
  name: "Speelhoek Raam"
  address: 0x0c
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Salon_Lijn_3
  name: "Salon Lijn 3"
  address: 0x0d
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Salon_Lijn_1
  name: "Salon Lijn 1"
  address: 0x0e
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Salon_Lijn_2
  name: "Salon Lijn 2"
  address: 0x0f
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Salon_Lijn_4
  name: "Salon Lijn 4"
  address: 0x10
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Bureau_Lijn
  name: "Bureau Lijn"
  address: 0x11
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Eettafel
  name: "Eettafel"
  address: 0x12
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: WC
  name: "WC"
  address: 0x13
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Keukenkast
  name: "Keukenkast"
  address: 0x14
  restore_mode: RESTORE_AND_OFF

- platform: dali
  id: Keuken_Group
  name: "Keuken"
  address: 0x40

- platform: dali
  id: Salon_Group
  name: "Salon Lijnen"
  address: 0x41

- platform: dali
  id: Gang_Group
  name: "Gang"
  address: 0x42

output:


button:
- platform: restart
  name: "Restart Device"


dali:
  id: dali_bus
  tx_pin: 14
  rx_pin: 5
  discovery: ${dali_discovery}  # If set, dali_light components will automatically be created from devices found on the bus
  initialize_addresses: false  # If set, unassigned devices will be automatically assigned an address
